---

- name: Ensure postgres-exporter is installed
  tags:
    - setup-all
    - setup-postgres-exporter
    - install-all
    - install-postgres-exporter
  block:
    - name: Include postgres-exporter config validation tasks
      when: postgres_exporter_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Include postgres-exporter installation tasks
      when: postgres_exporter_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Ensure postgres-exporter is removed
  tags:
    - setup-all
    - setup-postgres-exporter
  block:
    - name: Include postgres-exporter removal tasks
      when: not postgres_exporter_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
